import React from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle, Shield, ArrowRight, Phone, Circle, Sparkles, Thermometer, Paintbrush } from 'lucide-react';
import SEO from '../components/SEO';

const WheelCaliper: React.FC = () => {
  const benefits = [
    {
      icon: <Shield className="w-8 h-8 text-blue-900" />,
      title: 'Brake Dust Protection',
      description: 'Ceramic coating on wheels repels brake dust, making cleaning easier and keeping wheels looking cleaner longer.'
    },
    {
      icon: <Thermometer className="w-8 h-8 text-blue-900" />,
      title: 'Heat Resistant',
      description: 'High-temperature ceramic coatings withstand the extreme heat generated by braking systems.'
    },
    {
      icon: <Paintbrush className="w-8 h-8 text-blue-900" />,
      title: 'Custom Caliper Colors',
      description: 'Transform your brake calipers with professional powder coating or high-temp paint in any color.'
    },
    {
      icon: <Sparkles className="w-8 h-8 text-blue-900" />,
      title: 'Enhanced Appearance',
      description: 'Give your vehicle a custom, high-end look with professionally finished wheels and calipers.'
    }
  ];

  const wheelServices = [
    'Wheel ceramic coating',
    'Wheel face polishing',
    'Curb rash repair',
    'Wheel refinishing',
    'Barrel coating',
    'Lug nut coating',
    'Tire dressing',
    'Wheel cleaning service'
  ];

  const caliperServices = [
    'Caliper powder coating',
    'High-temp caliper paint',
    'Caliper ceramic coating',
    'Custom color matching',
    'Logo/text stenciling',
    'Caliper cleaning',
    'Bracket coating',
    'Hardware refinishing'
  ];

  const caliperColors = [
    { name: 'Red', hex: '#DC2626' },
    { name: 'Yellow', hex: '#EAB308' },
    { name: 'Blue', hex: '#2563EB' },
    { name: 'Black', hex: '#171717' },
    { name: 'Orange', hex: '#EA580C' },
    { name: 'Green', hex: '#16A34A' },
    { name: 'Silver', hex: '#A1A1AA' },
    { name: 'Gold', hex: '#CA8A04' }
  ];

  return (
    <>
      <SEO
        title="Wheel & Caliper Services Denver | Wheel Coating | Caliper Paint"
        description="Professional wheel and caliper services in Denver. Wheel ceramic coating, caliper powder coating, custom colors. Brake dust protection. Free quotes."
        keywords="wheel coating Denver, caliper painting Denver, brake caliper powder coating, wheel ceramic coating, custom caliper colors"
        canonical="https://example.com/wheel-caliper"
      />
      <section className="py-24 bg-white px-4 md:px-16">
        <div className="max-w-7xl mx-auto">
        
        {/* Hero Section */}
        <div className="mb-20">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <span className="text-blue-900 font-bold tracking-wider text-sm uppercase">WHEEL & CALIPER</span>
              <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mt-4 mb-6">
                Wheel & Caliper Services | Complete the Look
              </h1>
              <div className="w-20 h-1 bg-yellow-500 mb-6"></div>
              <p className="text-lg text-gray-600 mb-8 leading-relaxed">
                Elevate your vehicle's appearance with professional wheel coating and custom caliper finishing. Our services protect against brake dust and add a custom touch that sets your ride apart.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link to="/contact" className="bg-blue-900 hover:bg-blue-800 text-white font-bold py-4 px-8 rounded-xl transition-all transform hover:scale-105 shadow-lg flex items-center justify-center gap-2 group">
                  Get Free Quote
                  <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </Link>
                <a href="tel:9706186183" className="border-2 border-blue-900 text-blue-900 hover:bg-blue-900 hover:text-white font-bold py-4 px-8 rounded-xl transition-all flex items-center justify-center gap-2">
                  <Phone className="w-5 h-5" />
                  Call Us
                </a>
              </div>
            </div>
            <div className="relative">
              <div className="overflow-hidden h-[500px] md:h-[600px] rounded-2xl shadow-2xl bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center">
                <div className="text-center text-gray-400">
                  <Circle className="w-32 h-32 mx-auto mb-4" />
                  <p className="text-lg">Wheel & Caliper Services</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Benefits Section */}
        <div className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Why Coat Your Wheels & Calipers?</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Professional wheel and caliper services combine protection with customization for a complete upgrade.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {benefits.map((benefit, idx) => (
              <div 
                key={idx}
                className="bg-gray-50 rounded-2xl p-8 text-center hover:bg-blue-50 transition-colors duration-300 border border-gray-100"
              >
                <div className="bg-white p-4 rounded-full inline-flex mb-6 shadow-sm">
                  {benefit.icon}
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">{benefit.title}</h3>
                <p className="text-gray-600 leading-relaxed text-sm">{benefit.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Services Lists */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-20">
          <div className="bg-gradient-to-br from-blue-900 to-blue-800 rounded-2xl p-10">
            <h3 className="text-2xl font-bold text-white mb-6">Wheel Services</h3>
            <div className="space-y-4">
              {wheelServices.map((service, idx) => (
                <div key={idx} className="flex items-start">
                  <CheckCircle className="w-5 h-5 text-yellow-400 mr-3 flex-shrink-0 mt-0.5" />
                  <span className="text-white">{service}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="bg-gradient-to-br from-blue-900 to-blue-800 rounded-2xl p-10">
            <h3 className="text-2xl font-bold text-white mb-6">Caliper Services</h3>
            <div className="space-y-4">
              {caliperServices.map((service, idx) => (
                <div key={idx} className="flex items-start">
                  <CheckCircle className="w-5 h-5 text-yellow-400 mr-3 flex-shrink-0 mt-0.5" />
                  <span className="text-white">{service}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Caliper Colors Section */}
        <div className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Popular Caliper Colors</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Choose from our popular colors or request a custom color match.
            </p>
          </div>
          <div className="grid grid-cols-4 md:grid-cols-8 gap-4">
            {caliperColors.map((color, idx) => (
              <div key={idx} className="text-center">
                <div 
                  className="w-16 h-16 mx-auto rounded-full shadow-lg mb-2 border-4 border-white"
                  style={{ backgroundColor: color.hex }}
                ></div>
                <p className="text-sm font-medium text-gray-700">{color.name}</p>
              </div>
            ))}
          </div>
          <p className="text-center text-gray-500 text-sm mt-6">
            Custom colors available upon request. We can match any color!
          </p>
        </div>

        {/* Process Section */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 mb-20">
          <div className="bg-gray-50 rounded-2xl p-8 md:p-10">
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Wheel Coating Process</h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              Professional preparation ensures lasting protection.
            </p>
            <ul className="space-y-3">
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Wheel removal and inspection</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Deep cleaning and decontamination</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Surface preparation and polish</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Ceramic coating application</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Curing and reinstallation</span>
              </li>
            </ul>
          </div>
          <div className="bg-gray-50 rounded-2xl p-8 md:p-10">
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Caliper Coating Process</h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              High-temperature coating that lasts.
            </p>
            <ul className="space-y-3">
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Caliper removal and cleaning</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Media blasting for adhesion</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">High-temp primer application</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Color coat and clear coat</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="w-5 h-5 text-blue-900 mr-3 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">Heat curing and reinstallation</span>
              </li>
            </ul>
          </div>
        </div>

        {/* CTA Section */}
        <div className="bg-gradient-to-br from-gray-50 to-blue-50 rounded-2xl p-12 md:p-16 text-center">
          <h3 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Ready to Upgrade Your Wheels?
          </h3>
          <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
            Contact us today for a free quote. Complete your vehicle's look with professional wheel and caliper services.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link to="/contact" className="bg-blue-900 hover:bg-blue-800 text-white font-bold py-4 px-8 rounded-xl transition-all transform hover:scale-105 shadow-lg flex items-center justify-center gap-2 group">
              Get Free Quote
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            <a href="tel:9706186183" className="border-2 border-blue-900 text-blue-900 hover:bg-blue-900 hover:text-white font-bold py-4 px-8 rounded-xl transition-all flex items-center justify-center gap-2">
              <Phone className="w-5 h-5" />
              Call Us
            </a>
          </div>
        </div>

        </div>
      </section>
    </>
  );
};

export default WheelCaliper;
